In [1]:
import numpy as np

In [45]:
data = np.genfromtxt('KAG_Conversion_Data.csv', delimiter=',', skip_header=1,dtype=str)
data1= np.genfromtxt('KAG_Conversion_Data.csv', delimiter=',', skip_header=1,dtype=float)

In [36]:
x= data[:,1]
unique_id= np.unique(x)
unique_id

array(['1178', '916', '936'], dtype='<U11')

In [65]:
#determining how many unique id and how many times the campaign run
unique_id,count=np.unique(x,return_counts=True)
print("unique id is",unique_id)
print('count is',count)

#numbers of unique id
print("Total Number of Unique id",unique_id.size)

unique id is ['1178' '916' '936']
count is [625  54 464]
Total Number of Unique id 3


In [66]:
#details explanation on how many times each program was run
print("The id",unique_id[0],"is run",count[0])
print("The id",unique_id[1],"is run",count[1])
print("The id",unique_id[2],"is run",count[2])

The id 1178 is run 625
The id 916 is run 54
The id 936 is run 464


In [37]:
age_group= data[:,3]
age_group

array(['30-34', '30-34', '30-34', ..., '45-49', '45-49', '45-49'],
      dtype='<U11')

In [44]:
unique_age_group=np.unique(age_group)
unique_age_group

array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [47]:
amount_spent=data1[:,8]
amount_spent

array([  1.42999995,   1.82000002,   0.        , ...,  40.28999949,
       198.7100005 , 165.6099987 ])

In [48]:
#the average
avg_amount_spent=np.mean(amount_spent)
avg_amount_spent

51.36065613141295

In [49]:
#the max
max_amount_spent=np.max(amount_spent)
max_amount_spent

639.9499981

In [50]:
#the min
max_amount_spent=np.min(amount_spent)
max_amount_spent

0.0

In [58]:
clicks=data1[:,7]
print(clicks)

[  1.   2.   0. ...  28. 135. 114.]


In [59]:
data1[:,0][data1[:,7]==max(clicks)]

array([1121814.])

In [67]:
#number of people who bought the product after seeing the ad 
bought_product=data1[:,10]
p_bought_product=np.sum(bought_product)
p_bought_product

1079.0

In [72]:
#the maximum number of purchases 
max_purchase=bought_product.max()
max_purchase

21.0

In [73]:
#number of people who bought the product after seeing the ad with max clicks
print(int(data1[:,10][data1[:,7]==max(clicks)]))

13


In [77]:
data[data[:,10]=="21"]

array([['1121104', '1178', '144533', '30-34', 'M', '16', '2080666',
        '202', '360.1500015', '40', '21']], dtype='<U11')